[env]
left_features = "rumcake/split-central rumcake/bluetooth rumcake/usb"
right_features = "rumcake/split-peripheral"
out = "target/binout/"

# CHECK

[tasks.check]
dependencies = ["check-left", "check-right"]

[tasks.check-left]
command = "cargo"
args = ["check", "--bin=central", "--features=${left_features}"]

[tasks.check-right]
command = "cargo"
args = ["check", "--bin=right", "--features=${right_features}"]


# BUILD

[tasks.build]
dependencies = ["build-left", "build-right"]

[tasks.create-output-dir]
command = "mkdir"
args = ["-p", "${out}"]

[tasks.build-left]
dependencies = ["create-output-dir", "compile-left"]
command = "cargo"
args = [
    "objcopy",
    "--quiet",
    "--bin=central",
    "--release",
    "--features=${left_features}",
    "--",
    "-O",
    "binary",
    "${out}/left.bin",
]

[tasks.build-right]
dependencies = ["create-output-dir", "compile-right"]
command = "elf2uf2-rs"
args = [
    "objcopy",
    "--quiet",
    "--bin=right",
    "--release",
    "--features=${right_features}",
    "--",
    "-O",
    "binary",
    "${out}/right.bin",
]

[tasks.compile-left]
command = "cargo"
args = ["build", "--bin=central", "--release", "--features=${left_features}"]

[tasks.compile-right]
command = "cargo"
args = ["build", "--bin=right", "--release", "--features=${right_features}"]


# INSTALL
[tasks.install]
dependencies = ["install-left", "install-right"]

[tasks.install-left]
dependencies = ["build-left"]
command = "cargo"
args = ["run", "--bin=central", "--release", "--features=${left_features}"]

[tasks.install-right]
dependencies = ["build-right"]
command = "cargo"
args = ["run", "--bin=right", "--release", "--features=${right_features}"]
