[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["runner", "/dev/sda"]

[build]
target = "thumbv7em-none-eabihf"
rustflags = [
  "-Z",
  "macro-backtrace",
  # test later
  # "-Z", "trap-unreachable"
]

[env]
DEFMT_LOG = "debug,rumcake::keyboard=off"
