[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["runner", "/dev/ignition_dfu"]

[build]
target = "thumbv6m-none-eabi"
rustflags = ["-Z", "macro-backtrace"]

[env]
DEFMT_LOG = "debug"
