[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = ["echo 'change with a runner command'"]

[build]
target = "thumbv7em-none-eabihf"
rustflags = ["-Z", "macro-backtrace"]

[env]
DEFMT_LOG = "debug,rumcake::keyboard=off"
